language: python
python:
  - 2.6
  - 2.7
  - 3.2
  - 3.3
  - 3.4
install:
  - pip install flake8 --use-mirrors
  - python setup.py install
before_script: flake8 praw
script: python setup.py test -s tests.BasicTest && python setup.py test -s tests.OAuth2Test && python setup.py test -s tests.ModeratorSubredditTest.test_mod_mail_send
